### PR TITLE
Fix errors after update to 2018.1

### LINKED ISSUE #187: Errors after update to 2018.1
Seems that these happen in non-js projects (php in this case), but break things like highlighting in js/ts projects too. Worked fine in 2017.3 right before the update.

Error while indexing \\ 
or 
Error while indexing P:\Project\something.php
```
To reindex this file IDEA has to be restarted: containingFile.originalFile.virtualFile must not be null
java.lang.IllegalStateException: containingFile.originalFile.virtualFile must not be null
	at com.emberjs.utils.PsiElementExtensionsKt.getOriginalVirtualFile(PsiElementExtensions.kt:13)
	at com.emberjs.navigation.EmberTestFinder.isTest(EmberTestFinder.kt:55)
	at com.intellij.testIntegration.TestFinderHelper.isTest(TestFinderHelper.java:59)
	at com.jetbrains.php.lang.psi.stubs.indexes.PhpUnitCoversIndex$1.map(PhpUnitCoversIndex.java:61)
	at com.jetbrains.php.lang.psi.stubs.indexes.PhpUnitCoversIndex$1.map(PhpUnitCoversIndex.java:52)
	at com.intellij.util.indexing.impl.MapReduceIndex.mapInput(MapReduceIndex.java:273)
	at com.intellij.util.indexing.VfsAwareMapReduceIndex.calculateUpdateData(VfsAwareMapReduceIndex.java:98)
	at com.intellij.util.indexing.impl.MapReduceIndex.update(MapReduceIndex.java:213)
	at com.intellij.util.indexing.FileBasedIndexImpl.updateSingleIndex(FileBasedIndexImpl.java:1646)
	at com.intellij.util.indexing.FileBasedIndexImpl.lambda$doIndexFileContent$19(FileBasedIndexImpl.java:1574)
	at com.intellij.openapi.fileTypes.impl.FileTypeManagerImpl.freezeFileTypeTemporarilyIn(FileTypeManagerImpl.java:523)
	at com.intellij.util.indexing.FileBasedIndexImpl.doIndexFileContent(FileBasedIndexImpl.java:1533)
	at com.intellij.util.indexing.FileBasedIndexImpl.indexFileContent(FileBasedIndexImpl.java:1517)
	at com.intellij.util.indexing.FileBasedIndexImpl.processRefreshedFile(FileBasedIndexImpl.java:1500)
	at com.intellij.util.indexing.FileBasedIndexProjectHandler.lambda$reindexRefreshedFiles$2(FileBasedIndexProjectHandler.java:190)
	at com.intellij.openapi.project.CacheUpdateRunner$MyRunnable.lambda$run$0(CacheUpdateRunner.java:230)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1134)
	at com.intellij.openapi.project.CacheUpdateRunner$MyRunnable.lambda$run$1(CacheUpdateRunner.java:246)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$1(CoreProgressManager.java:157)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:580)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:525)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:85)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:144)
	at com.intellij.openapi.project.CacheUpdateRunner$MyRunnable.run(CacheUpdateRunner.java:243)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:305)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

### PR DESCRIPTION
**Pull request by nether-cat**
This pull request fixes #187

### CODE REVIEW

**Comment by dwickern** [comment]
How did this happen? Was `virtualFile` `@NotNull` before and became `@Nullable` in a recent update?

File: src/main/kotlin/com/emberjs/utils/PsiElementExtensions.kt [hunk 1]
```diff
@@ -9,11 +9,11 @@ import com.intellij.psi.util.PsiFilter
 import java.util.*
 
 
-val PsiElement.originalVirtualFile: VirtualFile
+val PsiElement.originalVirtualFile: VirtualFile?
     get() = containingFile.originalFile.virtualFile
 
 val PsiElement.module: Module?
-    get() = originalVirtualFile.let { findModuleForFile(it, project) }
+    get() = originalVirtualFile.let { findModuleForFile(it!!, project) }
```
Comment (dwickern) [inline src/main/kotlin/com/emberjs/utils/PsiElementExtensions.kt]: I think this can be written
```kt
get() = originalVirtualFile?.let { findModuleForFile(it, project) }
```

**Comment by nether-cat** [comment]
Hi @dwickern! I don't know yet, what exactly causes PHP files to not have a `virtualFile` and why. But the getter could already have returned `null` in the past. See the highlighted code [here](https://github.com/JetBrains/intellij-community/blame/181.4203/platform/core-impl/src/com/intellij/psi/impl/source/PsiFileImpl.java#L142-L145). The [actual interface](https://github.com/JetBrains/intellij-community/blame/181.4203/platform/core-api/src/com/intellij/psi/PsiFileSystemItem.java#L36) doesn't have any annotations that claim `@NotNull` nor `@Null`.

**Comment by dwickern** [comment]
And here I thought kotlin had our back 😞
